
package views;

import java.awt.Color;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import models.User;

/**
 *
 * @author ADMIN
 */
public class ManHinhChinh_frm extends javax.swing.JFrame {

    private User us1;
    private JPanel panelchid;

    /**
     * Creates new form ManHinhChinh_frm
     */
    public ManHinhChinh_frm(User us) {
        initComponents();
        us1 = us;
        if (us1.getChucVu() == 1) {
            btnKH.setEnabled(false);
            btnSP.setEnabled(false);
            btnHD.setEnabled(false);
            btnNV.setEnabled(false);
            btnKM.setEnabled(false);
        }
//        setLocationRelativeTo(null);
        lblTenNV.setText(us.getTenUSer());
        setpanal(new view_BanHangSua14_Jpanel());
        btnBanHang.setForeground(Color.red);
    }

    private void setpanal(JPanel panel) {
        panelchid = panel;
        pnMain.removeAll();
        pnMain.add(panelchid);
        pnMain.validate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnMenu = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btn_TaiKhoan = new javax.swing.JLabel();
        lblTenNV = new javax.swing.JLabel();
        btnBanHang = new javax.swing.JLabel();
        btnKM = new javax.swing.JLabel();
        btnNV = new javax.swing.JLabel();
        btnSP = new javax.swing.JLabel();
        btnHD = new javax.swing.JLabel();
        btnKH = new javax.swing.JLabel();
        btnThoat = new javax.swing.JLabel();
        btnTKe = new javax.swing.JLabel();
        btnBaoHanh = new javax.swing.JLabel();
        pnMain = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnMenu.setBackground(new java.awt.Color(0, 102, 204));
        pnMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(102, 204, 255));

        btn_TaiKhoan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/usericon3.png"))); // NOI18N
        btn_TaiKhoan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_TaiKhoanMouseClicked(evt);
            }
        });

        lblTenNV.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTenNV.setText("TÊN NHÂN VIÊN");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(btn_TaiKhoan))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(lblTenNV, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_TaiKhoan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTenNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(8, 8, 8))
        );

        pnMenu.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 172, -1));

        btnBanHang.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBanHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Shopping-Cart-icon.png"))); // NOI18N
        btnBanHang.setText("BÁN HÀNG");
        btnBanHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBanHangMouseClicked(evt);
            }
        });
        pnMenu.add(btnBanHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 133, 148, -1));

        btnKM.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnKM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Ecommerce-Sale-icon.png"))); // NOI18N
        btnKM.setText("KHUYẾN MÃI");
        btnKM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnKMMouseClicked(evt);
            }
        });
        pnMenu.add(btnKM, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 255, 148, -1));

        btnNV.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnNV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Users-Name-icon.png"))); // NOI18N
        btnNV.setText("NHÂN VIÊN");
        btnNV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNVMouseClicked(evt);
            }
        });
        pnMenu.add(btnNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 316, 148, -1));

        btnSP.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/products.png"))); // NOI18N
        btnSP.setText("SẢN PHẨM");
        btnSP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSPMouseClicked(evt);
            }
        });
        pnMenu.add(btnSP, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 194, -1, -1));

        btnHD.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnHD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Ecommerce-Bill-icon.png"))); // NOI18N
        btnHD.setText("HÓA ĐƠN");
        btnHD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHDMouseClicked(evt);
            }
        });
        pnMenu.add(btnHD, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 438, 148, -1));

        btnKH.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnKH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/people-icon.png"))); // NOI18N
        btnKH.setText("KHÁCH HÀNG");
        btnKH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnKHMouseClicked(evt);
            }
        });
        pnMenu.add(btnKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 377, -1, -1));

        btnThoat.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/log-out-icon.png"))); // NOI18N
        btnThoat.setText("THOÁT");
        btnThoat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnThoatMouseClicked(evt);
            }
        });
        pnMenu.add(btnThoat, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 621, 148, 53));

        btnTKe.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTKe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Statistics-icon.png"))); // NOI18N
        btnTKe.setText("THỐNG KÊ");
        btnTKe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTKeMouseClicked(evt);
            }
        });
        pnMenu.add(btnTKe, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 560, 148, -1));

        btnBaoHanh.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBaoHanh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/FontAwesome-File-Shield-icon.png"))); // NOI18N
        btnBaoHanh.setText("BẢO HÀNH");
        btnBaoHanh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBaoHanhMouseClicked(evt);
            }
        });
        pnMenu.add(btnBaoHanh, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 499, 148, -1));

        pnMain.setLayout(new javax.swing.BoxLayout(pnMain, javax.swing.BoxLayout.LINE_AXIS));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnMain, javax.swing.GroupLayout.DEFAULT_SIZE, 654, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 673, Short.MAX_VALUE)
                    .addComponent(pnMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThoatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThoatMouseClicked
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(this, "Bạn Có Chắc Chắn Muốn Thoát Không !") != JOptionPane.YES_OPTION) {
            return;
        }
        System.exit(0);

    }//GEN-LAST:event_btnThoatMouseClicked

    private void btnBanHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBanHangMouseClicked
        // TODO add your handling code here:

        setpanal(new view_BanHangSua14_Jpanel());
        btnBanHang.setForeground(Color.red);
        btnBaoHanh.setForeground(Color.BLACK);
        btnHD.setForeground(Color.BLACK);
        btnKH.setForeground(Color.BLACK);
        btnNV.setForeground(Color.BLACK);
        btnKM.setForeground(Color.BLACK);
        btnSP.setForeground(Color.BLACK);
        btnTKe.setForeground(Color.BLACK);
    }//GEN-LAST:event_btnBanHangMouseClicked

    private void btnBaoHanhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBaoHanhMouseClicked
        // TODO add your handling code here:
        setpanal(new view_BaoHanh1());
        btnBanHang.setForeground(Color.BLACK);
        btnBaoHanh.setForeground(Color.RED);
        btnHD.setForeground(Color.BLACK);
        btnKH.setForeground(Color.BLACK);
        btnNV.setForeground(Color.BLACK);
        btnKM.setForeground(Color.BLACK);
        btnSP.setForeground(Color.BLACK);
        btnTKe.setForeground(Color.BLACK);
    }//GEN-LAST:event_btnBaoHanhMouseClicked

    private void btn_TaiKhoanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_TaiKhoanMouseClicked
        try {
            // TODO add your handling code here:
            setpanal(new view_TaiKhoan(us1));
        } catch (ParseException ex) {
            Logger.getLogger(ManHinhChinh_frm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_TaiKhoanMouseClicked

    private void btnHDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHDMouseClicked
        // TODO add your handling code here:
        if (us1.getChucVu() == 1) {
            JOptionPane.showMessageDialog(rootPane, "Không có quyền truy cập");
        } else {
            setpanal(new view_HoaDon());

        }
        btnBanHang.setForeground(Color.BLACK);
        btnBaoHanh.setForeground(Color.BLACK);
        btnHD.setForeground(Color.RED);
        btnKH.setForeground(Color.BLACK);
        btnNV.setForeground(Color.BLACK);
        btnKM.setForeground(Color.BLACK);
        btnSP.setForeground(Color.BLACK);
        btnTKe.setForeground(Color.BLACK);
    }//GEN-LAST:event_btnHDMouseClicked

    private void btnKHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKHMouseClicked
        // TODO add your handling code here:
        if (us1.getChucVu() == 1) {
            JOptionPane.showMessageDialog(rootPane, "Không có quyền truy cập");
        } else {
            setpanal(new view_KhachHang1());

        }
        btnBanHang.setForeground(Color.BLACK);
        btnBaoHanh.setForeground(Color.BLACK);
        btnHD.setForeground(Color.BLACK);
        btnKH.setForeground(Color.RED);
        btnNV.setForeground(Color.BLACK);
        btnKM.setForeground(Color.BLACK);
        btnSP.setForeground(Color.BLACK);
        btnTKe.setForeground(Color.BLACK);

    }//GEN-LAST:event_btnKHMouseClicked

    private void btnKMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKMMouseClicked
        // TODO add your handling code here:
        if (us1.getChucVu() == 1) {
            JOptionPane.showMessageDialog(rootPane, "Không có quyền truy cập");
        } else {
            setpanal(new view_KhuyenMai());

        }
        btnBanHang.setForeground(Color.BLACK);
        btnBaoHanh.setForeground(Color.BLACK);
        btnHD.setForeground(Color.BLACK);
        btnKH.setForeground(Color.BLACK);
        btnNV.setForeground(Color.BLACK);
        btnKM.setForeground(Color.RED);
        btnSP.setForeground(Color.BLACK);
        btnTKe.setForeground(Color.BLACK);

    }//GEN-LAST:event_btnKMMouseClicked

    private void btnSPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSPMouseClicked
        // TODO add your handling code here:
        if (us1.getChucVu() == 1) {
            JOptionPane.showMessageDialog(rootPane, "Không có quyền truy cập");
        } else {
            setpanal(new view_ChiTietDH_JPanel());
        }
        btnBanHang.setForeground(Color.BLACK);
        btnBaoHanh.setForeground(Color.BLACK);
        btnHD.setForeground(Color.BLACK);
        btnKH.setForeground(Color.BLACK);
        btnNV.setForeground(Color.BLACK);
        btnKM.setForeground(Color.BLACK);
        btnSP.setForeground(Color.red);
        btnTKe.setForeground(Color.BLACK);
    }//GEN-LAST:event_btnSPMouseClicked

    private void btnTKeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTKeMouseClicked
        // TODO add your handling code here:
        setpanal(new view_ThongKe1());
        btnBanHang.setForeground(Color.BLACK);
        btnBaoHanh.setForeground(Color.BLACK);
        btnHD.setForeground(Color.BLACK);
        btnKH.setForeground(Color.BLACK);
        btnNV.setForeground(Color.BLACK);
        btnKM.setForeground(Color.BLACK);
        btnSP.setForeground(Color.BLACK);
        btnTKe.setForeground(Color.RED);
    }//GEN-LAST:event_btnTKeMouseClicked

    private void btnNVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNVMouseClicked
        // TODO add your handling code here:
        if (us1.getChucVu() == 1) {
            JOptionPane.showMessageDialog(rootPane, "Không có quyền truy cập");
        } else {
            setpanal(new frm_Nhanvien());

        }
        btnBanHang.setForeground(Color.BLACK);
        btnBaoHanh.setForeground(Color.BLACK);
        btnHD.setForeground(Color.BLACK);
        btnKH.setForeground(Color.BLACK);
        btnNV.setForeground(Color.RED);
        btnKM.setForeground(Color.BLACK);
        btnSP.setForeground(Color.BLACK);
        btnTKe.setForeground(Color.BLACK);

    }//GEN-LAST:event_btnNVMouseClicked

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ManHinhChinh_frm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ManHinhChinh_frm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ManHinhChinh_frm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ManHinhChinh_frm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ManHinhChinh_frm().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnBanHang;
    private javax.swing.JLabel btnBaoHanh;
    private javax.swing.JLabel btnHD;
    private javax.swing.JLabel btnKH;
    private javax.swing.JLabel btnKM;
    private javax.swing.JLabel btnNV;
    private javax.swing.JLabel btnSP;
    private javax.swing.JLabel btnTKe;
    private javax.swing.JLabel btnThoat;
    private javax.swing.JLabel btn_TaiKhoan;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblTenNV;
    private javax.swing.JPanel pnMain;
    private javax.swing.JPanel pnMenu;
    // End of variables declaration//GEN-END:variables
}
